name: Build and deploy Streamlit Python app to Azure Web App - appdummytest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python version
      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      # Step 3: Create and start virtual environment
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Optional: Add step to run tests here (e.g., PyTest, etc.)

      # Step 5: Zip artifact for deployment
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      # Step 6: Upload artifact for deployment jobs
      - uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Step 1: Download artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      # Step 2: Unzip artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Step 3: Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'appdummytest' # Replace with your app's Azure Web App name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6498216F27D54846B1B7BEA1C7A31900 }}  # Replace with your publish profile secret
          startup-command: 'streamlit run app.py'  # Command to start your Streamlit app

      # Step 4: Azure logout (Optional for cleaning up session)
      - name: logout
        run: |
          az logout
